# Generated by Django 5.0.3 on 2024-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_candidate_constituency_delete_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
