# Generated by Django 5.0.3 on 2024-12-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_party_alter_constituency_id_alter_candidate_party'),
    ]

    operations = [
    ]
