# Generated by Django 5.0.3 on 2024-12-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20241215_2105'),
    ]

    operations = [
    ]
