# Generated by Django 5.0.3 on 2024-12-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20241215_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='constituencies',
            field=models.ManyToManyField(blank=True, related_name='parties_with_most_votes', to='members.constituency'),
        ),
    ]
