# Generated by Django 5.0.3 on 2024-12-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_party_constituencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='party_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
