# Generated by Django 5.0.3 on 2024-12-15 19:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_constituency_party_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
