# Generated by Django 5.0.3 on 2024-12-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_party_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constituency',
            name='total_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
