# Generated by Django 5.0.3 on 2024-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_constituency_current_round_constituency_total_rounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
