# Generated by Django 5.0.3 on 2024-12-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_constituency_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='incumbent_party',
            field=models.CharField(default='', max_length=20),
        ),
    ]
