# Generated by Django 5.0.3 on 2025-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_constituency_incumbent_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
