# Generated by Django 5.0.3 on 2026-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_candidate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='sno',
            field=models.IntegerField(default=0),
        ),
    ]
