# Generated by Django 5.0.3 on 2026-05-31 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_candidate_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('round_votes', models.PositiveIntegerField(default=0)),
                ('cumulative_votes', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='members.candidate')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_results', to='members.constituency')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('candidate', 'constituency', 'round_number')},
            },
        ),
    ]
