# Generated by Django 5.0.3 on 2026-05-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_roundresult'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roundresult',
            unique_together={('candidate', 'round_number')},
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='constituency',
        ),
    ]
