# Generated by Django 5.0.3 on 2026-05-31 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_alter_roundresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='votes',
        ),
    ]
