# Generated by Django 5.0.3 on 2026-05-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_constituency_result_declared'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
