# Generated by Django 5.0.3 on 2026-05-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_party_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('unrecognised', 'Unrecognised')], default='state', max_length=20),
        ),
    ]
