# Generated by Django 5.0.3 on 2026-06-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_party_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='postal_votes',
            field=models.IntegerField(default=0),
        ),
    ]
